export const POPULAR_GOOGLE_FONTS = [
  "Roboto",
  "Open Sans",
  "Noto Sans",
  "Montserrat",
  "Lato",
  "Poppins",
  "Inter",
  "Oswald",
  "Raleway",
  "Nunito",
  "Ubuntu",
  "Playfair Display",
  "Rubik",
  "Merriweather",
  "Work Sans",
  "Lora",
  "Fira Sans",
  "Quicksand",
  "Mulish",
  "Inconsolata",
  "PT Sans",
  "Mukta",
  "DM Sans",
  "Noto Serif",
  "Heebo",
  "Libre Franklin",
  "Kanit",
  "Anton",
  "Josefin Sans",
  "Karla",
  "Arimo",
  "Teko",
  "Caveat",
  "Asap",
  "Fjalla One",
  "Pacifico",
  "Dancing Script",
  "Outfit",
  "Space Grotesk",
  "Manrope",
  "Syne",
  "Plus Jakarta Sans",
  "Bebas Neue",
  "Righteous",
  "Cinzel",
  "Cormorant Garamond",
  "Crimson Pro",
  "Fira Code",
  "JetBrains Mono",
  "Space Mono",
].sort()
